### ISSUE TITLE
Consider connection over I2P 

### ISSUE THREAD

**Issue by TNTBOMBOM** [digitalautonomy/wahay#24]
I2P has many benefits over Tor for e.g:

- P2P (Tor is not p2p).
- Support UDP and TCP (Tor only TCP) , This is beneficially specially for VOIP. 
- Support IPv4 and IPv6 (Tor lately started to support some of IPv6, But mainly its IPv4).

I dont say to deprecate Tor , But having both wont harm and useful as well to use different paths of secure communications.

**Comment by olabiniV2** [comment]
Hi, thank you for the suggestion, but we have no immediate plans to supports I2P. The goal of Wahay is to specifically combine the benefits of Tor onion services with Mumble, and adding support for I2P would significantly increase the complexity of the application. Our point of view is that having both _will_ actually harm the application, since the attack surface will be greatly increased without improving features in a way that balances that out.

If you are interested in I2P, you could of course fork Wahay and change the Tor support for I2P, but it's not something we are likely to do.
